# Generated by Django 5.2.14 on 2026-05-22 16:09

import apps.platform.accounts.handoff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_accounts', '0002_oauth_provider_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoffSigningKey',
            fields=[
                ('id', models.UUIDField(default=apps.platform.accounts.handoff.models._new_uuid, editable=False, primary_key=True, serialize=False)),
                ('key_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('secret', models.TextField(editable=False)),
                ('algorithm', models.CharField(default='HS256', editable=False, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promoted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('retired_at', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'handoff signing key',
                'verbose_name_plural': 'handoff signing keys',
                'indexes': [models.Index(condition=models.Q(('retired_at__isnull', True)), fields=['-created_at'], name='handoff_signing_key_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('retired_at__isnull', True), ('retired_at__gt', models.F('created_at')), _connector='OR'), name='handoff_signing_key_retired_after_created')],
            },
        ),
    ]
