# Generated by Django 5.2.14 on 2026-05-26 18:06

import apps.platform.accounts.impersonation.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_accounts', '0003_handoffsigningkey'),
        ('platform_organizations', '0002_membershipscopeassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationSession',
            fields=[
                ('id', models.UUIDField(default=apps.platform.accounts.impersonation.models._new_session_uuid, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(help_text='Business reason for impersonation (B.7).')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('ADMIN_ENDED', 'Admin ended'), ('LOGOUT', 'Logout'), ('EXPIRED', 'Expired')], default='', help_text='Why the session ended. Empty string while active; set when ended_at is set.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_user', models.ForeignKey(help_text='Platform admin performing the impersonation (B.7).', on_delete=django.db.models.deletion.PROTECT, related_name='impersonation_sessions_initiated', to=settings.AUTH_USER_MODEL)),
                ('ended_by_user', models.ForeignKey(blank=True, help_text='User who ended the session. NULL while session is active.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impersonation_sessions_ended', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(help_text='The specific membership being assumed. Anchors the session to a (user, org) pair that was ACTIVE at start time.', on_delete=django.db.models.deletion.PROTECT, related_name='impersonation_sessions', to='platform_organizations.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impersonation_sessions', to='platform_organizations.organization')),
                ('target_user', models.ForeignKey(help_text='User being impersonated.', on_delete=django.db.models.deletion.PROTECT, related_name='impersonation_sessions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'impersonation session',
                'verbose_name_plural': 'impersonation sessions',
                'indexes': [models.Index(fields=['admin_user', 'started_at'], name='impers_admin_started_idx'), models.Index(fields=['target_user', 'started_at'], name='impers_target_started_idx'), models.Index(fields=['organization', 'started_at'], name='impers_org_started_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('admin_user', models.F('target_user')), _negated=True), name='impers_admin_not_target'), models.CheckConstraint(condition=models.Q(('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='impers_ended_after_started'), models.CheckConstraint(condition=models.Q(models.Q(('ended_at__isnull', True), ('ended_by_user__isnull', True)), models.Q(('ended_at__isnull', False), ('ended_by_user__isnull', False)), _connector='OR'), name='impers_ended_pair_together'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('admin_user',), name='impers_one_active_per_admin')],
            },
        ),
    ]
