# Generated by Django 5.2.14 on 2026-05-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='membership',
            new_name='platform_or_user_id_875b18_idx',
            old_name='platform_or_user_id_org_idx',
        ),
        migrations.RenameIndex(
            model_name='membership',
            new_name='platform_or_organiz_3be403_idx',
            old_name='platform_or_org_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='organization',
            new_name='platform_or_status_69be1d_idx',
            old_name='platform_or_status_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantdeletionrequest',
            new_name='platform_or_organiz_0691f9_idx',
            old_name='platform_or_org_status_del_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantdeletionrequest',
            new_name='platform_or_status_3cc955_idx',
            old_name='platform_or_status_grace_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantexportrequest',
            new_name='platform_or_organiz_b6098d_idx',
            old_name='platform_or_org_id_status_xpt_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantexportrequest',
            new_name='platform_or_status_d5352e_idx',
            old_name='platform_or_status_expires_idx',
        ),
    ]
