# Generated by Django 5.2.14 on 2026-05-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platform_rbac', '0002_seed_v1'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='capability',
            new_name='platform_rb_categor_12db84_idx',
            old_name='platform_rb_categ_idx',
        ),
        migrations.RenameIndex(
            model_name='capability',
            new_name='platform_rb_is_depr_f907a0_idx',
            old_name='platform_rb_dep_idx',
        ),
        migrations.RenameIndex(
            model_name='membershipcapabilitygrant',
            new_name='platform_rb_members_a57d92_idx',
            old_name='platform_rb_memb_grant_idx',
        ),
        migrations.RenameIndex(
            model_name='membershiprole',
            new_name='platform_rb_members_70053c_idx',
            old_name='platform_rb_memb_idx',
        ),
        migrations.RenameIndex(
            model_name='role',
            new_name='platform_rb_organiz_802f8c_idx',
            old_name='platform_rb_org_def_idx',
        ),
    ]
